apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-initdb-scripts
data:
  init.js: |
    db = db.getSiblingDB("integradora");
    db.createUser({
      user: "admin",
      pwd: "admin123",
      roles: [{ role: "readWrite", db: "integradora" }]
    });
